### ISSUE TITLE
Use async/await

### ISSUE THREAD

**Issue by the-pat** [the-pat/reddit-node-wallpaper#10]
Update to use async/await rather than synchronous calls.

Currently the module uses promises and synchronous calls (i.e. `fs.mkdirSync`), the module could be improved by using async calls.

**Comment by ArfatSalman** [comment]
Hi 
Can you describe the issue a little more? 

Thanks

**Comment by aparrett** [comment]
I would like to claim this issue.

**Comment by the-pat** [comment]
@ArfatSalman I updated the issue. If you'd like, I would accept a pull request that uses the async version of the `fs` methods (I can make another issue if that would help).

@aparrett thanks for the PR!

**Comment by aparrett** [comment]
Looks like I should have waited for clarification haha I will gladly make the appropriate changes if @ArfatSalman does not respond today.

Neat tool by the way!

**Comment by ArfatSalman** [comment]
@the-pat Yes. I would like to work on it. 🙂 

So, Scanning `index.js`, I see that we are still using `existsSync`, `mkdirSync`, and `renameSync`. I need to use the async version of these. Am I correct in my understanding? 

Thanks

**Comment by the-pat** [comment]
@ArfatSalman you are correct in your understanding! I am excited to get your PR.

@aparrett no worries! Feel free to add any features you think the tool could use.
